### ISSUE TITLE
How is this licensed please?

### ISSUE THREAD

**Issue by samuk** [RobertLukan/rpi-cm4-custom-board#1]
Hi looks like a great board. I couldn't spot a licence for it?

Do you plan to use an open hardware license for it such as https://ohwr.org/cern_ohl_p_v2.txt or similar?

**Comment by RobertLukan** [comment]
I will be honest with you, I have no idea about this topic. My idea is to share this with anyone and anyone can use. So I guess the most permissive license would work ?

**Comment by samuk** [comment]
I like the CERN permissive license linked above personally, obviously up to you though..

**Comment by RobertLukan** [comment]
Ok good to know. I will update the Readme.
